from magenta.models.performance_rnn import performance_sequence_generator
from magenta.models.shared import sequence_generator_bundle

from note_seq.protobuf import generator_pb2
from note_seq.protobuf import music_pb2
from note_seq import midi_io
import note_seq  #https://github.com/magenta/note-seq
import os


def generate_sequence(selected_model):

    # downloaded mag files from here
    # https://github.com/magenta/magenta/tree/master/magenta/models/performance_rnn
    BUNDLE_DIR = './models/'
    MODEL_NAME = selected_model # stored in models folder
    # one of
    # these models have different embedding representations
    # performance - ignores note velocities but models note on/off events with expressive timing
    # performance_with_dynamics - model includes velocity changes quantized into 32 bins
    # performance_with_dynamics_and_modulo_encoding - model uses an alternate encoding where event values are mapped to points on the unit circle.
    # conditional models with desired density, pitch or both.
    # density_conditioned_performance_with_dynamics
    # pitch_conditioned_performance_with_dynamics
    # multiconditioned_performance_with_dynamics
    BUNDLE_NAME = MODEL_NAME + '.mag'

    bundle = sequence_generator_bundle.read_bundle_file(os.path.join(BUNDLE_DIR, BUNDLE_NAME))

    generator_map = performance_sequence_generator.get_generator_map()
    generator = generator_map[MODEL_NAME](checkpoint=None, bundle=bundle)
    generator.initialize()
    generator_options = generator_pb2.GeneratorOptions()
    generator_options.args['temperature'].float_value = 1.0  # Higher is more random; 1.0 is default. Try 0.9 to 2.0
    generate_section = generator_options.generate_sections.add(start_time=0, end_time=30)

    sequence = generator.generate(music_pb2.NoteSequence(), generator_options) # magic , log likelihood -3794.191895
    midi_io.note_sequence_to_midi_file(sequence,'./midi_files/generated_music_v4.mid')

    return sequence


note_seq.play_sequence(sequence, note_seq.midi_synth.fluidsynth,
                 sf2_path='/tmp/Yamaha-C5-Salamander-JNv5.1.sf2')

def make_music(model, details, input_seq, generator_options):
    """

    :param model: instance of Performance Rnn Model
    :param details: Generator details for the Performance Rnn model
    :param input_seq: input sequence generated by the user (type unsure??) # todo
    :param generator_options: Options to use for the generation

    :return: generated sequence (type unsure??) #todo

    reference: https://colab.research.google.com/notebooks/magenta/performance_rnn/performance_rnn.ipynb
    """



    performance_sequence_generator(model, # an instance of PerformanceRnnModel # todo: what types of models are there?
                                   details, # generator_pb2.GeneratorDetails for this generator
                                   steps_per_second=100,
                                   num_velocity_bins=0,
                                   control_signals=None,
                                   optional_conditioning=False,
                                   max_note_duration=5.0, # force forget of notes by setting this
                                   fill_generate_section=True, # sequence length determined not estimated
                                   checkpoint=None, #
                                   bundle=None,
                                   note_performance=False)

    note_sequence_proto = performance_sequence_generator.generate(input_seq, generator_options)